### ISSUE TITLE
cmake doesn't install from pip

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue-env-targets#137]
```bash
Collecting cmake
  Downloading https://files.pythonhosted.org/packages/a5/7c/6525cadf99abbabbcb29676f53de0441e8d2f8d0114ab52aae2b31223a3b/cmake-3.16.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-JW5e_R/cmake/setup.py", line 7, in <module>
        from skbuild import setup
    ImportError: No module named skbuild
```
https://travis-ci.com/tue-robotics/action_server/jobs/295947314#L2624

**Comment by ar13pit** [comment]
This is an issue with tue-install-pip. The local pip version isn't being updated. I tested it out on a clean docker container.
